apiVersion: v1
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: minimal-notebook
      name: minimal-notebook
    spec:
      replicas: 1
      selector:
        app: minimal-notebook
        deploymentconfig: minimal-notebook
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: minimal-notebook
            deploymentconfig: minimal-notebook
        spec:
          containers:
            - image: jupyter-image:latest
              name: minimal-notebook
              ports:
                - containerPort: 8888
                  protocol: TCP
              resources: {}
              volumeMounts:
                - name: jovyan-data
                  mountPath: /home/jovyan
          volumes:
            - name: jovyan-data
              emptyDir: {}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - minimal-notebook
            from:
              kind: ImageStreamTag
              name: jupyter-image:latest
              namespace: jup
          type: ImageChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: minimal-notebook
      name: minimal-notebook
    spec:
      ports:
        - name: 8888-tcp
          port: 8888
          protocol: TCP
          targetPort: 8888
      selector:
        app: minimal-notebook
        deploymentconfig: minimal-notebook
    status:
      loadBalancer: {}
kind: List
metadata: {}
