---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jupyter-storage-class
provisioner: no-provisioning
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jupyter-storage-class
  hostPath:
    path: /mnt/data/jupyter-vol
